# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3daf20fc6056cc5d3707317f4cd1fa9885b86be42f0f59de10fb6460d530573add963ff570ef977dde72cbbc33c6652872fa79346c3af8404001550dc160f1d

test:
  secret_key_base: 26e80ab1f959365acad6fef21ad0173578b40f995282fc9803b1a04fb2ea50f4a8456b4d471b0f7416a0e8da05b5eb3b626e7218ae70337f172a7a9b5d8dafaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
